/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "error": "#ba1a1a",
        "surface": "#f8f9fb",
        "on-primary-fixed": "#001453",
        "inverse-surface": "#2e3132",
        "tertiary-fixed-dim": "#ffb59a",
        "surface-container-highest": "#e1e2e4",
        "secondary-fixed": "#d8e2ff",
        "on-background": "#191c1e",
        "on-tertiary-fixed-variant": "#802a00",
        "on-secondary-fixed": "#001a42",
        "on-surface": "#191c1e",
        "on-tertiary-container": "#ffa583",
        "tertiary-container": "#872d00",
        "on-tertiary-fixed": "#380d00",
        "primary-fixed-dim": "#b8c4ff",
        "inverse-on-surface": "#f0f1f3",
        "outline": "#757684",
        "secondary": "#0058be",
        "on-error-container": "#93000a",
        "surface-dim": "#d9dadc",
        "primary-fixed": "#dde1ff",
        "primary-container": "#1e40af",
        "outline-variant": "#c4c5d5",
        "surface-tint": "#3755c3",
        "on-primary-fixed-variant": "#173bab",
        "on-secondary-fixed-variant": "#004395",
        "error-container": "#ffdad6",
        "on-surface-variant": "#444653",
        "surface-variant": "#e1e2e4",
        "secondary-fixed-dim": "#adc6ff",
        "surface-container-high": "#e7e8ea",
        "secondary-container": "#2170e4",
        "on-tertiary": "#ffffff",
        "surface-bright": "#f8f9fb",
        "tertiary-fixed": "#ffdbce",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#fefcff",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "background": "#f8f9fb",
        "on-primary-container": "#a8b8ff",
        "surface-container-low": "#f3f4f6",
        "inverse-primary": "#b8c4ff",
        "surface-container": "#edeef0",
        "primary": "#00288e",
        "on-primary": "#ffffff",
        "tertiary": "#611e00"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "manrope": ["Manrope", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
